import React, { useEffect, useState } from 'react';
import { Button, Form, Input, Select, Table, Card, Typography, Divider, Tag, Checkbox, notification, Switch } from 'antd'; // Ensure Tag is imported
import { PlusOutlined, TeamOutlined } from '@ant-design/icons';
import API from '../CustomHooks/MasterApiHooks/api';
import { useTranslation } from 'react-i18next';
import themeStore from './../store/themeStore';
import { useStore } from 'zustand';
import { Modal } from 'react-bootstrap';

const { Option } = Select;
const { Title, Text } = Typography;

const Team = () => {
  const { t } = useTranslation();
  const { getCssClasses } = useStore(themeStore);
  const cssClasses = getCssClasses();
  const [customDark, customMid, customLight, customBtn, customDarkText, customLightText, customLightBorder, customDarkBorder] = cssClasses;
  const [isModalVisible, setIsModalVisible] = useState(false);
  const [form] = Form.useForm();
  const [users, setUsers] = useState([]);
  const [teams, setTeams] = useState([]);
  const [showDescription, setShowDescription] = useState(false); // State to manage description column visibility, default is hidden
  const [editingTeam, setEditingTeam] = useState(null); // State to manage the team being edited

  const getUsers = async () => {
    try {
      const response = await API.get('/User/operator');
      setUsers(response.data);
    } catch (error) {
      console.error("Failed to fetch Users");
    }
  };

  const getTeams = async () => {
    try {
        const response = await API.get('/Teams'); // Updated API endpoint to fetch teams
        setTeams(response.data); // Set the teams data from the API response

        // Map userIds to userNames
        const userMap = {};
        teams.forEach(team => {
            team.users.forEach(user => {
                userMap[user.id] = user.name; // Map userId to userName
            });
        });

        // Update teams with userNames
        const updatedTeams = teams.map(team => ({
            ...team,
            userNames: team.users.map(user => userMap[user.id] || '').join(', '), // Construct userNames from userIds
        }));

        setTeams(updatedTeams); // Set the updated teams with userNames
    } catch (error) {
        console.error("Failed to fetch Teams", error); // Log the error for debugging
        notification.error({
            message: 'Error',
            description: 'Failed to fetch teams or user details. Please check the API endpoints.',
        });
    }
};

  const handleOk = async () => {
    form
      .validateFields()
      .then(async (values) => {
        const newTeam = {
          teamId: 0, // Assuming teamId is auto-generated by the backend
          teamName: values.teamName,
          description: values.description || '', // Optional description
          createdDate: new Date().toISOString(), // Current date in ISO format
          status: true, // Assuming the team is active
          userIds: values.teamMembers, // Use userIds from the form
          userNames: values.teamMembers.map(id => users.find(user => user.userId === id)?.firstName).join(', '), // Construct userNames from selected userIds
        };

        try {
          await API.post('/Teams', newTeam); // Send the request to create the team
          setTeams([...teams, newTeam]); // Update the state with the new team
          setIsModalVisible(false);
          form.resetFields(); // Reset the form fields after submitting

          // Show success notification
          notification.success({
            message: 'Team Created',
            description: `The team "${newTeam.teamName}" has been created successfully!`,
            placement: 'topRight', // Position of the notification
          });
        } catch (error) {
          console.error("Failed to create Team", error);
        }
      })
      .catch((info) => {
        console.error('Form validation failed:', info);
      });
  };

  const handleEdit = (team) => {
    setEditingTeam(team);
    form.setFieldsValue({
      teamName: team.teamName,
      description: team.description,
      teamMembers: team.users.map(user => user.id),
    });
    setIsModalVisible(true);
  };

  const handleStatusChange = async (teamId, status) => {
    const teamToUpdate = teams.find(t => t.teamId === teamId);
    if (!teamToUpdate) return; // Ensure the team exists

    const updatedTeam = {
        ...teamToUpdate,
        status: status, // Update the status
    };

    try {
        await API.put(`/Teams/${teamId}`, updatedTeam); // Ensure the correct API endpoint is used
        // Update the local state to reflect the new status
        setTeams(prevTeams => 
            prevTeams.map(team => (team.teamId === teamId ? updatedTeam : team))
        );
        // Show success notification for status change
        notification.success({
            message: 'Team Status Updated',
            description: `The team status has been updated successfully!`,
            placement: 'topRight',
        });
    } catch (error) {
        console.error("Failed to update Team status", error);
    }
};

  const handleUpdate = async () => {
    form
      .validateFields()
      .then(async (values) => {
        const updatedTeam = {
          teamId: editingTeam.teamId,
          teamName: values.teamName,
          description: values.description || '',
          createdDate: editingTeam.createdDate, // Keep the original created date
          status: editingTeam.status, // Keep the original status
          userIds: values.teamMembers,
          userNames: values.teamMembers.map(id => users.find(user => user.userId === id)?.firstName).join(', '),
        };

        try {
          await API.put(`/Teams/${editingTeam.teamId}`, updatedTeam);
          setTeams(teams.map(team => (team.teamId === editingTeam.teamId ? updatedTeam : team)));
          setIsModalVisible(false);
          form.resetFields();

          // Show success notification for update
          notification.success({
            message: 'Team Updated',
            description: `The team "${updatedTeam.teamName}" has been updated successfully!`,
            placement: 'topRight',
          });
        } catch (error) {
          console.error("Failed to update Team", error);
        }
      })
      .catch((info) => {
        console.error('Form validation failed:', info);
      });
  };

  // Define table columns dynamically based on showDescription state
  const columns = React.useMemo(() => {
    const baseColumns = [
      {
        title: 'SN',
        dataIndex: 'sn',
        key: 'sn',
        render: (text, record, index) => index + 1,
      },
      {
        title: 'Team Name',
        dataIndex: 'teamName',
        key: 'teamName',
      },
      {
        title: 'Members',
        dataIndex: 'userNames', // Use userNames from the API response
        key: 'userNames',
        render: (userNames) => (
            <>
                {userNames ? userNames.split(', ').map((name, index) => (
                    <Tag key={index}>{name}</Tag> // Render user names in tags
                )) : <span>No members</span>} 
            </>
        ),
    },
      {
        title: 'Status',
        dataIndex: 'status',
        key: 'status',
        render: (status, record) => (
          <Switch
            checked={status}
            onChange={(checked) => handleStatusChange(record.teamId, checked)} // Ensure correct teamId is passed
          />
        ),
      },
      {
        title: 'Action',
        key: 'action',
        render: (text, record) => (
          <Button onClick={() => handleEdit(record)} type="link">
            Edit
          </Button>
        ),
      },
    ];

    if (showDescription) {
      baseColumns.splice(2, 0, {
          title: 'Description',
          dataIndex: 'description',
          key: 'description',
      });
  }

  return baseColumns;
}, [showDescription]);
  useEffect(() => {
    getUsers();
    getTeams(); // Fetch teams when the component mounts
  }, []);

  return (
    <div style={{ padding: '40px' }}>
      <Card style={{ boxShadow: '0 4px 8px rgba(0,0,0,0.1)', borderRadius: '10px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '20px' }}>
          <Button onClick={() => setIsModalVisible(true)} size="large" className={`${customBtn} ${customDark === "dark-dark" ? `border` : `border-0`}`}>
            Add Team
          </Button>
          <Checkbox
            checked={showDescription}
            onChange={(e) => setShowDescription(e.target.checked)}
            style={{ marginLeft: 'auto' }}
          >
            Show Description
          </Checkbox>
        </div>

        <Divider>Existing Teams</Divider>
        <Table
          columns={columns}
          dataSource={teams.map((team, index) => ({
            ...team,
            key: index,
          }))} // Ensure each team has a unique key
          pagination={false}
          bordered
          style={{ marginTop: '20px' }}
          rowClassName={(record, index) => (index % 2 === 0 ? 'table-row-light' : 'table-row-dark')}
        />
      </Card>

      <Modal
        show={isModalVisible}
        onHide={() => {
          setIsModalVisible(false);
          setEditingTeam(null);
          form.resetFields();
        }}
        centered
        className={`{}`}
      >
        <Modal.Header closeButton={false} className={customDark}>
          <Modal.Title className={`${customLightText}`}>{editingTeam ? 'Edit Team' : 'Add New Team'}</Modal.Title>
        </Modal.Header>
        <Modal.Body className={customMid}>
          <Form form={form} layout="vertical" name="addTeamForm">
            <Form.Item
              label={<span className={customDarkText}>Team Name</span>}
              name="teamName"
              rules={[{ required: true, message: 'Please enter the team name!' }]}
            >
              <Input placeholder="Enter team name" size="large" />
            </Form.Item>

            <Form.Item
              label={<span className={customDarkText}>Description</span>}
              name="description"
            >
              <Input placeholder="Enter team description" size="large" />
            </Form.Item>

            <Form.Item
              label={<span className={customDarkText}>Team Members</span>}
              name="teamMembers"
              rules={[{ required: true, message: 'Please select team members!' }]}
            >
              <Select
                mode="multiple"
                placeholder="Select team members"
                allowClear
                size="large"
              >
                {users.map((user) => (
                  <Option key={user.userId} value={user.userId}>
                    {user.firstName} {user.middleName} {user.lastName}
                  </Option>
                ))}
              </Select>
            </Form.Item>
          </Form>
        </Modal.Body>
        <Modal.Footer className={customDark}>
          <Button onClick={() => {
            setIsModalVisible(false);
            setEditingTeam(null);
            form.resetFields();
          }}>
            Cancel
          </Button>
          <Button className={`${customBtn}`} onClick={editingTeam ? handleUpdate : handleOk}>
            {editingTeam ? 'Update Team' : 'Add Team'}
          </Button>
        </Modal.Footer>
      </Modal>
    </div>
  );
};

export default Team;